export const WATCHLIST_REQUEST = "WATCHLIST_REQUEST";
export const WATCHLIST_SUCCESS = "WATCHLIST_SUCCESS";
export const WATCHLIST_FAIL = "WATCHLIST_FAIL";

export const STOCK_ADD_REQUEST = "STOCK_ADD_REQUEST";
export const STOCK_ADD_SUCCESS = "STOCK_ADD_SUCCESS";
export const STOCK_ADD_FAIL = "STOCK_ADD_FAIL";

export const STOCK_EDIT_REQUEST = "STOCK_EDIT_REQUEST";
export const STOCK_EDIT_SUCCESS = "STOCK_EDIT_SUCCESS";
export const STOCK_EDIT_FAIL = "STOCK_EDIT_FAIL";

export const STOCK_DELETE_REQUEST = "STOCK_DELETE_REQUEST";
export const STOCK_DELETE_SUCCESS = "STOCK_DELETE_SUCCESS";
export const STOCK_DELETE_FAIL = "STOCK_DELETE_FAIL";
